inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/ExtraSpacing:
  AllowBeforeTrailingComments: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
